trigger:
- master

resources:
- repo: self

variables:
  cliversion: 0.9.2
  tag: 'azuredevops-$(Build.BuildNumber)'
  imageName: 'mend/container-scanning-demo'

stages:
- stage: Build
  displayName: Build, Scan and Push image
  jobs:  
  - job: Build
    displayName: Build, Scan and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker hub'
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/src/'
        tags: '$(tag)'

    - task: CmdLine@2
      displayName: "Run MendCLI scan"
      inputs:
        script: |
            mendcli image --severity LOW,MEDIUM $(imageName):$(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker hub'
        repository: '$(imageName)'
        command: 'push'
        tags: '$(tag)'
